### PR TITLE
Ensure the gem works on Rails 4.2

### PR DESCRIPTION
**Pull request by cbliard**
On Rails 4.2, the ActiveSupport notification payload does not include
any `:type_casted_binds`. This was introduced in Rails 5.0. Thus when the
matcher does not match, it fails to display its message with the following
error:

    NoMethodError:
    undefined method `any?' for nil:NilClass

It happens while evaluating `query[:binds].any?` because `query[:binds]`
is `nil`.

This commit casts the values in `payload[:binds]` to have the same
behavior as with Rails 5.x

Also introduce appraisal to test from Rails 4.2 to 5.1

Also restricted Rails version to be '> 4.2' because specs fail with
Rails 4.1.

### CODE REVIEW

**Comment by cbliard** [comment]
It's the first time I'm using the appraisal gem. I took inspiration from the awesome_print gem. I hope this will work as expected on Travis.

**Comment by nepalez** [comment]
@cbliard Thank you! That's wonderful

**Comment by cbliard** [comment]
My pleasure :)
